# Generated by Django 3.0.1 on 2020-03-09 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_no', models.CharField(max_length=15)),
                ('product_title', models.CharField(max_length=30)),
                ('product_brand', models.CharField(default='.', max_length=30)),
                ('product_image1', models.ImageField(upload_to='propics')),
                ('product_discount_price', models.IntegerField(blank=True, null=True)),
                ('product_price', models.IntegerField(default=0)),
                ('product_description', models.TextField(max_length=150)),
                ('product_quantity', models.IntegerField(default=1)),
                ('product_offer', models.BooleanField(default=False)),
                ('product_category', models.CharField(choices=[('BD', 'BREAD'), ('MK', 'MILK'), ('EG', 'EGG')], default='..', max_length=4)),
                ('product_label', models.CharField(choices=[('NW', 'NEW'), ('BS', 'BEST-SELLER')], default='..', max_length=4)),
                ('delievery_charges', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(default='test-product')),
                ('total_orders', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('product_quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=15, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(to='product.OrderProduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
