# Generated by Django 3.0.1 on 2020-03-10 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_quantity',
            new_name='quantity',
        ),
    ]
