# Generated by Django 3.0.1 on 2020-03-15 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200315_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delievery_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Address'),
        ),
    ]
