# Generated by Django 3.0.1 on 2020-03-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200315_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Payment_option',
            new_name='payment_option',
        ),
    ]
